from __future__ import annotations

from enum import Enum


class ActionType(str, Enum):
    READ_DOCUMENT = "READ_DOCUMENT"
    EXTRACT_STRUCTURED_DATA = "EXTRACT_STRUCTURED_DATA"
    LOCATE_TARGETS = "LOCATE_TARGETS"
    FILL_FIELDS = "FILL_FIELDS"
    UPDATE_TABLE = "UPDATE_TABLE"
    SUMMARIZE_CONTENT = "SUMMARIZE_CONTENT"
    COMPARE_DOCUMENTS = "COMPARE_DOCUMENTS"
    VALIDATE_OUTPUT = "VALIDATE_OUTPUT"
    CREATE_OUTPUT = "CREATE_OUTPUT"
    BUILD_FIELD_MAPPING = "BUILD_FIELD_MAPPING"
    SCAN_TEMPLATE_FIELDS = "SCAN_TEMPLATE_FIELDS"